/*
 * SUSTech Store API
 *
 * API service for SUSTech Store
 *
 * API version: 0.1.0
 * Contact: 12110304@mail.sustech.edu.cn
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CreateOrderRequest struct {
	ProductId int32 `json:"product_id" required:"true"`

	Quantity int32 `json:"quantity" required:"true"`
}
