/*
 * SUSTech Store API
 *
 * API service for SUSTech Store
 *
 * API version: 0.1.0
 * Contact: 12110304@mail.sustech.edu.cn
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type LoginRequest struct {
	Username string `json:"username" required:"true"`

	Password string `json:"password" required:"true"`
}
