/*
 * SUSTech Store API
 *
 * API service for SUSTech Store
 *
 * API version: 0.1.0
 * Contact: 12110304@mail.sustech.edu.cn
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Product struct {
	Id int32 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`

	Category string `json:"category,omitempty"`

	Price float64 `json:"price,omitempty"`

	Slogan string `json:"slogan,omitempty"`

	Stock int32 `json:"stock,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`
}
