/*
 * SUSTech Store API
 *
 * API service for SUSTech Store
 *
 * API version: 0.1.0
 * Contact: 12110304@mail.sustech.edu.cn
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RegisterUserRequest struct {

	// Student ID must be 8 digits
	Sid string `json:"sid" validate:"regexp=^\\\\d{8}$"`

	Username string `json:"username"`

	// Valid email address
	Email string `json:"email,omitempty" validate:"regexp=^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{2,}$"`

	Password string `json:"password"`
}
