# 1 deployment - 4 pod replicas - 1 flask server per pod
# 1 service to expose the deployment above

apiVersion: apps/v1
kind: Deployment
metadata:
  name: a4t0
spec:
  replicas: 4
  selector:
    matchLabels:
      app: a4t0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: a4t0
    spec:
      containers: # each pod will have the following containers
        - name: flask-containers
          image: a4-flask:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: a4t0-service
spec:
  selector: # this service manages pods with this label only 
    app: a4t0
  ports:
    - protocol: TCP
      port: 80 # port for the service
      targetPort: 5000 # port that the pods are listening on
  type: ClusterIP # Service accessible only within the cluster
