/*
 * SUSTech Store API
 *
 * API service for SUSTech Store
 *
 * API version: 0.1.0
 * Contact: 12110304@mail.sustech.edu.cn
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"log"
	"octcarp/sustech/cs328/a2/api/config"
	sw "octcarp/sustech/cs328/a2/api/router"
)

func main() {
	cfg := config.GetConfig()
	routes := sw.ApiHandleFunctions{}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	addr := fmt.Sprintf("%s:%d", cfg.Api.Host, cfg.Api.Port)
	log.Fatal(router.Run(addr))
}
