# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glog.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'glog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nglog.proto\x12\x04glog\"w\n\nLogMessage\x12\x1d\n\x05level\x18\x01 \x01(\x0e\x32\x0e.glog.LogLevel\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08trace_id\x18\x05 \x01(\t\"/\n\x0bLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*7\n\x08LogLevel\x12\x08\n\x04INFO\x10\x00\x12\x0b\n\x07WARNING\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\t\n\x05\x44\x45\x42UG\x10\x04\x32\x45\n\x0eLoggingService\x12\x33\n\nStreamLogs\x12\x10.glog.LogMessage\x1a\x11.glog.LogResponse(\x01\x42\tZ\x07glog/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007glog/pb'
  _globals['_LOGLEVEL']._serialized_start=190
  _globals['_LOGLEVEL']._serialized_end=245
  _globals['_LOGMESSAGE']._serialized_start=20
  _globals['_LOGMESSAGE']._serialized_end=139
  _globals['_LOGRESPONSE']._serialized_start=141
  _globals['_LOGRESPONSE']._serialized_end=188
  _globals['_LOGGINGSERVICE']._serialized_start=247
  _globals['_LOGGINGSERVICE']._serialized_end=316
# @@protoc_insertion_point(module_scope)
